version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq_host
    privileged: true
    ports:
      - "15672:15672"   # web UI 管理接口
      - "5672:5672"    # 生产者和消费者连接使用的接口
    volumes:
      - ./docker/rabbit/data:/var/lib/rabbitmq/mnesia #挂载 RabbitMQ数据
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
  etcd:
    image: bitnami/etcd:3.5
    container_name: etcdstore
    restart: always
    hostname: etcd_host
    ports:
      - "2379:2379"
      - "2380:2380"
      - "4001:4001"
    volumes:
      - ./docker/etcdstore/data:/bitnami/etcdstore/data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcdstore:2379

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./build/config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
